### PR TITLE
0.29.1 h917bf1

### PR DESCRIPTION
**Pull request by vincentmr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vincentmr** [comment]
@leofang I couldn't push to the regro branch so I opened another PR, is that OK?

**Comment by vincentmr** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
> @leofang I couldn't push to the regro branch so I opened another PR, is that OK?

Sure, no problem, but it's odd that you can't push to the bot's branch. I checked you're a maintainer, so you should have access.

**Review by leofang — APPROVED** [review]
LGTM! Thanks, Vincent!

**Comment by vincentmr** [comment]
> > @leofang I couldn't push to the regro branch so I opened another PR, is that OK?
> 
> Sure, no problem, but it's odd that you can't push to the bot's branch. I checked you're a maintainer, so you should have access.

I got 

```
(venv) vincent.michaud-rioux@xanaduinfra-Latitude-7420:~/repos/pennylane-lightning-gpu-feedstock$ git push regro
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 8 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 834 bytes | 834.00 KiB/s, done.
Total 8 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 3 local objects.
To github.com:regro-cf-autotick-bot/pennylane-lightning-gpu-feedstock.git
 ! [remote rejected] 0.29.1_h917bf1 -> 0.29.1_h917bf1 (permission denied)
error: failed to push some refs to 'git@github.com:regro-cf-autotick-bot/pennylane-lightning-gpu-feedstock.git'
```

Are there branch restrictions maybe?

**Comment by leofang** [comment]
Yeah maybe don't push the entire repo, just push a specific branch? Like
```
git push regro branch_name
```

**Pull request merged**
