### PR TITLE
Release v0.35.0

### PR DESCRIPTION
**Pull request by vincentmr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vincentmr** [comment]
@conda-forge-admin, please rerender

**Comment by vincentmr** [comment]
@conda-forge-admin, please rerender

**Comment by vincentmr** [comment]
@conda-forge-admin, please rerender

**Comment by vincentmr** [comment]
@leofang , we fully switched to CUDA-12 in the latest release, so I disabled the CUDA-11 builds. `conda-smithy` has trouble rerendering the recipe, do you know how to do that?

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by vincentmr** [comment]
I'm also wondering how to trigger the Python 3.12 migration. Could you please point me to the doc if you know where it is?

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
> I'm also wondering how to trigger the Python 3.12 migration. Could you please point me to the doc if you know where it is?

In theory the bot should send a PR automatically, but it seems to hit some error:
截圖 2024-03-11 下午4 47 16
https://conda-forge.org/status/migration/python312

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
My bad, I missed what the bot said:
> I tried to rerender for you but ran into some issues.

It is likely that the same bug is leading to both issues (CUDA 11 & Python 3.12). @vincentmr maybe you need to debug via running conda-smithy locally...

**Comment by vincentmr** [comment]
Locally if I modify `.ci_support/migrations/cuda120.yaml` to include `11.8` and set the condition to `skip: true  # [py==38 or (not linux) or ((cuda_compiler_version or "").startswith("11"))]`, `conda-smithy` produces a seemingly valid commit. Should I push it?

**Comment by vincentmr** [comment]
It also said 

> WARNING: Setting build platform [...] I trust that you know what you're doing.

which is why I pinged you :D

**Comment by leofang** [comment]
Ahhh yes good idea, I've lost my sense on CF packaging stuff... plz copy/paste https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/cuda120.yaml to `.ci_support/migrations/cuda120.yaml` and rerender

**Comment by vincentmr** [comment]
> Ahhh yes good idea, I've lost my sense on CF packaging stuff... plz copy/paste https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/cuda120.yaml to `.ci_support/migrations/cuda120.yaml` and rerender

Nice, that's what I was looking for. I guess I could use the python312 file too if the bot doesn't manage to finalize the migration?

**Comment by leofang** [comment]
There are CI files carrying the name `cuda_compilerNone` but they should not be there. Seems like there's a loophole in the skip logic...?

> I guess I could use the python312 file too if the bot doesn't manage to finalize the migration?

Yes. If the bot does not act, you can try adding the `python312` file and rerender locally, see what happens.

**Comment by vincentmr** [comment]
> There are CI files carrying the name `cuda_compilerNone` but they should not be there. Seems like there's a loophole in the skip logic...?

Yep, you're right. I think I fixed it with the last commit.

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
> Ahhh yes good idea, I've lost my sense on CF packaging stuff... plz copy/paste https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/cuda120.yaml to `.ci_support/migrations/cuda120.yaml` and rerender

Q: @vincentmr have you forgotten to check in changes in `cuda120.yaml`?

**Comment by vincentmr** [comment]
> > Ahhh yes good idea, I've lost my sense on CF packaging stuff... plz copy/paste https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/cuda120.yaml to `.ci_support/migrations/cuda120.yaml` and rerender
> 
> Q: @vincentmr have you forgotten to check in changes in `cuda120.yaml`?

Oh, yes. I guess I need to push that too.

**Comment by leofang** [comment]
Yup, otherwise all automation infrastructure would fail. Thanks!

**Pull request merged**
