### PR TITLE
Update Maintainers

### PR DESCRIPTION
**Pull request by maliasadi**
Checklist

- [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
 - [x]  Bumped the build number (if the version is unchanged)
 - [x] Reset the build number to `0` (if the version changed)
 - [x]  [Re-rendered](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks) with the latest `conda-smithy` (Use the phrase `@conda-forge-admin, please rerender` in a comment in this PR for automated rerendering)
 - [x]  Ensured the license file is being packaged.

### CODE REVIEW

**Review by leofang — CHANGES_REQUESTED** [review]
This is not the way to update maintainers. Please add your ID to recipe/meta.yaml and rerender.

**Comment by maliasadi** [comment]
@conda-forge-admin, please rerender

**Comment by maliasadi** [comment]
@conda-forge-admin, please rerender

**Comment by maliasadi** [comment]
@conda-forge-admin, please rerender.

**Comment by vincentmr** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
